<a href="https://colab.research.google.com/github/alishas2005/alishass/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import LeaveOneOut, LeavePOut, KFold,StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

In [2]:
dataset = pd.read_csv("/content/placement.csv")

In [3]:
dataset.head(3)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [5]:
x =  dataset.iloc[:,:-1]
y = dataset["resume_score"]

In [6]:
new_data = dataset.head()

In [20]:
lo = KFold(n_splits=5)
for train, test in lo.split(x_new,y_new):
  print(train,test)

[1 2 3 4] [0]
[0 2 3 4] [1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


In [10]:
x_new = new_data.iloc[:,:-1]
y_new = new_data["resume_score"]

In [12]:
new_data

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [30]:
p=cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits=10))

In [31]:
p.sort()
p*100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])